# Generated by Django 3.2.6 on 2023-07-13 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Students_Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_id', models.CharField(max_length=100, null=True)),
                ('number', models.CharField(max_length=100, null=True)),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=100, null=True)),
                ('body', models.TextField(max_length=300, null=True)),
                ('student_name', models.CharField(max_length=100, null=True)),
                ('student_class', models.CharField(max_length=100, null=True)),
                ('student_place_of_birth', models.CharField(max_length=100, null=True)),
                ('student_date_of_birth', models.DateField()),
                ('student_nisn', models.CharField(max_length=100, null=True)),
                ('type_sign', models.CharField(choices=[('1', 'Digital Sign'), ('2', 'Manual Sign')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('digital_sign_at', models.DateTimeField(auto_now=True)),
                ('digital_sign_by', models.CharField(max_length=100, null=True)),
                ('digital_sign_job_title', models.CharField(max_length=100, null=True)),
                ('digital_sign_institution', models.CharField(max_length=100, null=True)),
                ('digital_sign_location', models.CharField(max_length=100, null=True)),
                ('digital_sign_ip', models.CharField(max_length=100, null=True)),
                ('digital_sign_number', models.CharField(max_length=100, null=True)),
                ('digital_sign_url', models.CharField(max_length=100, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_models_letter', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_models_letter', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
