# Generated by Django 3.2.6 on 2023-07-14 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students_Letter',
        ),
    ]
