# Generated by Django 3.2.6 on 2023-07-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students_letter',
            old_name='is_selected_for_destroy',
            new_name='is_selected_to_destroy',
        ),
    ]
