# Generated by Django 3.2.6 on 2023-07-14 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('letter', '0002_delete_students_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students_Letter',
            fields=[
                ('letter_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, max_length=500, null=True)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_class', models.CharField(blank=True, max_length=50, null=True)),
                ('student_place_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('student_date_of_birth', models.DateField()),
                ('student_nisn', models.CharField(blank=True, max_length=20, null=True)),
                ('type_sign', models.CharField(blank=True, choices=[('1', 'Digital Sign'), ('2', 'Manual Sign')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('digital_sign_at', models.DateTimeField(blank=True, null=True)),
                ('digital_sign_job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('digital_sign_institution', models.CharField(blank=True, max_length=100, null=True)),
                ('digital_sign_location', models.CharField(blank=True, max_length=100, null=True)),
                ('digital_sign_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('digital_sign_number', models.CharField(blank=True, max_length=50, null=True)),
                ('digital_sign_url', models.URLField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_students_letters', to=settings.AUTH_USER_MODEL)),
                ('digital_sign_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digital_signed_students_letters', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_students_letters', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
