# Generated by Django 3.2.6 on 2023-07-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0002_rename_is_selected_for_destroy_students_letter_is_selected_to_destroy'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_letter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
