# Generated by Django 3.2.6 on 2023-08-08 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('letter', '0003_students_letter_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_letter',
            name='body',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='Employees_Letter',
            fields=[
                ('letter_id', models.AutoField(primary_key=True, serialize=False)),
                ('letter_type', models.CharField(blank=True, choices=[('1', 'Surat Tugas'), ('2', 'Surat Keterangan')], max_length=1, null=True)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body_opening', models.TextField(blank=True, max_length=250, null=True)),
                ('body_purpose', models.TextField(blank=True, max_length=325, null=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('time_start', models.CharField(blank=True, max_length=50, null=True)),
                ('time_end', models.CharField(blank=True, max_length=50, null=True)),
                ('place_address', models.CharField(blank=True, max_length=600, null=True)),
                ('employee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_place_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_date_of_birth', models.DateField()),
                ('employee_rank', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_gender', models.CharField(blank=True, choices=[('1', 'Laki-laki'), ('2', 'Perempuan')], max_length=1, null=True)),
                ('employee_empnumber', models.CharField(blank=True, max_length=20, null=True)),
                ('type_sign', models.CharField(blank=True, choices=[('1', 'Digital Sign'), ('2', 'Manual Sign')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('digital_sign_at', models.DateTimeField(blank=True, null=True)),
                ('digital_sign_by_name', models.CharField(blank=True, max_length=150, null=True)),
                ('digital_sign_job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('digital_sign_institution', models.CharField(blank=True, max_length=100, null=True)),
                ('digital_sign_location', models.CharField(blank=True, max_length=1000, null=True)),
                ('digital_sign_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('digital_sign_number', models.CharField(blank=True, max_length=512, null=True)),
                ('digital_sign_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('qr_code_base64', models.TextField(blank=True, null=True)),
                ('is_selected_to_destroy', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees_letters', to=settings.AUTH_USER_MODEL)),
                ('digital_sign_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digital_signed_employees_letters', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_employees_letters', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
