# Generated by Django 3.2.6 on 2023-07-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0004_alter_students_letter_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_letter',
            name='letter_type',
            field=models.CharField(blank=True, choices=[('1', 'Digital Sign'), ('2', 'Manual Sign')], max_length=1, null=True),
        ),
    ]
