# Generated by Django 3.2.6 on 2023-08-14 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('letter', '0005_alter_employees_letter_letter_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Common_Letter',
            fields=[
                ('letter_id', models.AutoField(primary_key=True, serialize=False)),
                ('letter_type', models.CharField(blank=True, choices=[('1', 'Surat Undangan')], max_length=1, null=True)),
                ('letter_category', models.CharField(blank=True, choices=[('1', 'Rahasia'), ('2', 'Segera'), ('3', 'Biasa'), ('4', 'Penting Segera'), ('5', 'Penting')], max_length=1, null=True)),
                ('dear_invitation', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body_opening', models.TextField(blank=True, max_length=250, null=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('time_start', models.CharField(blank=True, max_length=50, null=True)),
                ('time_end', models.CharField(blank=True, max_length=50, null=True)),
                ('place_address', models.CharField(blank=True, max_length=600, null=True)),
                ('event_name', models.CharField(blank=True, max_length=100, null=True)),
                ('body_closing', models.TextField(blank=True, max_length=325, null=True)),
                ('type_sign', models.CharField(blank=True, choices=[('1', 'Digital Sign'), ('2', 'Manual Sign')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('digital_sign_at', models.DateTimeField(blank=True, null=True)),
                ('digital_sign_by_name', models.CharField(blank=True, max_length=150, null=True)),
                ('digital_sign_job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('digital_sign_institution', models.CharField(blank=True, max_length=100, null=True)),
                ('digital_sign_location', models.CharField(blank=True, max_length=1000, null=True)),
                ('digital_sign_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('digital_sign_number', models.CharField(blank=True, max_length=512, null=True)),
                ('digital_sign_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('qr_code_base64', models.TextField(blank=True, null=True)),
                ('is_selected_to_destroy', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_common_letters', to=settings.AUTH_USER_MODEL)),
                ('digital_sign_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digital_signed_common_letters', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_common_letters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
