# Generated by Django 3.2.6 on 2023-07-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0005_students_letter_letter_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_letter',
            name='letter_type',
            field=models.CharField(blank=True, choices=[('1', 'Surat Keterangan'), ('2', 'Surat Rekomendasi')], max_length=1, null=True),
        ),
    ]
