# Generated by Django 3.2.6 on 2023-07-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0006_alter_students_letter_letter_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_letter',
            name='digital_sign_ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students_letter',
            name='digital_sign_location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
