# Generated by Django 3.2.6 on 2023-08-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0006_common_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='common_letter',
            name='is_in_staging',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employees_letter',
            name='is_in_staging',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='students_letter',
            name='is_in_staging',
            field=models.BooleanField(default=True),
        ),
    ]
