# Generated by Django 3.2.6 on 2023-10-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0007_auto_20230819_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_letter',
            name='student_gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
