# Generated by Django 3.2.6 on 2023-07-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0007_auto_20230721_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_letter',
            name='digital_sign_by_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
