# Generated by Django 3.2.6 on 2023-10-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0008_alter_students_letter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees_letter',
            name='employee_gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
