# Generated by Django 3.2.6 on 2023-07-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0008_students_letter_digital_sign_by_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_letter',
            name='digital_sign_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
