# Generated by Django 3.2.6 on 2023-07-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0009_alter_students_letter_digital_sign_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_letter',
            name='digital_sign_number',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
