# Generated by Django 3.2.6 on 2023-10-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0009_alter_employees_letter_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees_letter',
            name='employee_empnumber',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
