# Generated by Django 3.2.6 on 2023-07-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0010_alter_students_letter_digital_sign_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_letter',
            name='student_gender',
            field=models.CharField(blank=True, choices=[('1', 'Surat Keterangan'), ('2', 'Surat Rekomendasi')], max_length=1, null=True),
        ),
    ]
