# Generated by Django 3.2.6 on 2023-10-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0010_alter_employees_letter_employee_empnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_letter',
            name='letter_type',
            field=models.CharField(blank=True, choices=[('1', 'Surat Keterangan')], max_length=1, null=True),
        ),
    ]
