# Generated by Django 3.2.6 on 2023-07-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0011_students_letter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_letter',
            name='qr_code_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students_letter',
            name='student_gender',
            field=models.CharField(blank=True, choices=[('1', 'Laki-laki'), ('2', 'Perempuan')], max_length=1, null=True),
        ),
    ]
