# Generated by Django 3.2.6 on 2023-07-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0012_auto_20230722_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_letter',
            name='digital_sign_ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='students_letter',
            name='digital_sign_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
