# Generated by Django 3.2.6 on 2024-02-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0012_auto_20231018_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='common_letter',
            name='is_destroyed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employees_letter',
            name='is_destroyed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='students_letter',
            name='is_destroyed',
            field=models.BooleanField(default=False),
        ),
    ]
