# Generated by Django 3.2.6 on 2024-02-15 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('letter', '0014_auto_20240215_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='common_letter',
            name='desrtoyed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destroyed_common_letters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employees_letter',
            name='destroyed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destroyed_employees_letters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='students_letter',
            name='destroyed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destroyed_students_letters', to=settings.AUTH_USER_MODEL),
        ),
    ]
