# Generated by Django 3.2.6 on 2024-02-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0015_auto_20240215_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='common_letter',
            name='destroyed_by_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='employees_letter',
            name='destroyed_by_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='students_letter',
            name='destroyed_by_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
