# Generated by Django 3.2.6 on 2023-07-06 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrations',
            fields=[
                ('integration_id', models.AutoField(primary_key=True, serialize=False)),
                ('server_address', models.CharField(max_length=200, null=True)),
                ('npsn', models.CharField(max_length=200, null=True)),
                ('token', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
